name: gbeuzeboc-listener
version: '0.1'
summary: Basic ROS2 listener
description: |
  Basic ROS2 listener based on core20

grade: stable
confinement: strict
base: core20

plugs:
  gbeuzeboc-talker:
    interface: content
    target: $SNAP/gbeuzeboc-talker
    default-provider: gbeuzeboc-talker

parts:
  gbeuzeboc-listener:
    plugin: colcon
    source: .
    stage-packages: [ros-foxy-ros2launch, ros-foxy-ros2service, ros-foxy-ros2run, ros-foxy-ros2doctor]
  
  config:
    plugin: dump
    source: config/
    organize:
      '*': usr/share/robot-config/

apps:
  gbeuzeboc-talker-listener-daemon:
    daemon: simple
    command: opt/ros/foxy/bin/ros2 launch listener talker_listener.launch.py
    post-stop-command: opt/ros/snap/lib/listener/ros_doctor
    plugs: [network, network-bind]
    extensions: [ros2-foxy]
    environment:
      "LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/gbeuzeboc-talker/lib/talker"
      "AMENT_PREFIX_PATH": "$AMENT_PREFIX_PATH:$SNAP/gbeuzeboc-talker/snap" # we source our additional workspace
